### ISSUE TITLE
Issue Downloading pyBigWig

### ISSUE THREAD

**Issue by tdb7dgr** [deeptools/pyBigWig#144]
Hi,

I'm having an issue downloading pyBigWig, and I don't know enough about downloading packages through terminal to understand what the issue is. I used "pip install pyBigWig" to try to download the package, but it is running into a subprocess error. I don't know what I should do to fix this error. What do you suggest I do? Below, I included the error message.

Thank you!

(C:\Users\Totoro\anaconda3) C:\Users\Totoro>pip install pyBigWig
Collecting pyBigWig
  Using cached pyBigWig-0.3.22.tar.gz (73 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Totoro\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Totoro\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Totoro\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Totoro\AppData\Local\Temp\pip-build-env-vub7n6h8\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Totoro\AppData\Local\Temp\pip-build-env-vub7n6h8\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Totoro\AppData\Local\Temp\pip-build-env-vub7n6h8\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by dpryan79** [comment]
You're not going to be able to easily install this (or many other packages) on windows unless you're using WSL2.
